const toggleButton = document.querySelector('[data-toggle]');
const toggleButtonHalfmoon = document.querySelector('[data-toggle-halfmoon]');
const headerButton = document.querySelector('[data-header-button]');
const headerButtonIn = document.querySelector('[data-header-button-in]');
const dreamHouseButton = document.querySelector('[data-dreamhouse-button]');
const dreamHouseTitle = document.querySelector('[data-dreamhouse-title]');
const dreamHouseText = document.querySelector('[data-dreamhouse-text]');
const archmoveButton = document.querySelector('[data-archmove-button]');
const dreamProjectButton = document.querySelector('[data-dream-project-button]');
const headerLogo = document.querySelector('[data-header-logo]');
const footerLogo = document.querySelector('[data-footer-logo]');
const body = document.querySelector('[data-body]');
const container = document.querySelector('[data-container]');
const designTitle = document.querySelector('[data-design-title]');
const archmoveTitle = document.querySelector('[data-archmove-title]');
const archmoveText = document.querySelector('[data-archmove-text]');
const dreamProjectText = document.querySelector('[data-dream-project-text]');
const linkGallery = document.querySelector('[data-link-gallery]');
const linkList = document.querySelector('[data-link-list]');
const linkArticles = document.querySelector('[data-link-articles]');
const linkWorks = document.querySelector('[data-link-works]');
const iconBird = document.querySelector('[data-icon-bird]');
const iconDollar = document.querySelector('[data-icon-dollar]');
const iconCircle = document.querySelector('[data-icon-circle]');
toggleButton.addEventListener('click', () => {
    headerButtonIn.classList.toggle('header__buttons__sign--in--night');
    headerButton.classList.toggle('night');
    dreamHouseButton.classList.toggle('night');
    archmoveButton.classList.toggle('night');
    dreamProjectButton.classList.toggle('night');
    headerLogo.classList.toggle('night');
    footerLogo.classList.toggle('night');
    toggleButton.classList.toggle('night');
    toggleButtonHalfmoon.classList.toggle('halfmoon--hidden');
    body.classList.toggle('night');
    container.classList.toggle('night');
    dreamHouseTitle.classList.toggle('night');
    dreamHouseText.classList.toggle('night');
    designTitle.classList.toggle('night');
    archmoveTitle.classList.toggle('night');
    archmoveText.classList.toggle('night');
    dreamProjectText.classList.toggle('night');
    linkGallery.classList.toggle('night');
    linkList.classList.toggle('night');
    linkArticles.classList.toggle('night');
    linkWorks.classList.toggle('night');
    iconBird.classList.toggle('night');
    iconDollar.classList.toggle('night');
    iconCircle.classList.toggle('night');
});
